### PR TITLE
Support Python 3.13

### LINKED ISSUE #96: Test failure in test_filehandler_reopen_thread_safety on Python 3.13
### What I did:

1. Check out current `master`, abf6f26fd27b79a23978058b274e397cca72b504
2. Run `tox -e py313`

### What I expect to happen:

All tests pass, as they do for `tox -e py312`.

### What actually happened:

```
Failure in test test_filehandler_reopen_thread_safety (ZConfig.components.logger.tests.test_logger.TestReopeningLogfiles.test_filehandler_reopen_thread_safety)
Traceback (most recent call last):
  File "/usr/lib64/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib64/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
  File "/home/ben/src/forks/ZConfig/src/ZConfig/components/logger/tests/test_logger.py", line 714, in test_filehandler_reopen_thread_safety
    self.assertEqual(calls, ["acquire", "acquire", "release", "release"])
  File "/usr/lib64/python3.13/unittest/case.py", line 907, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.13/unittest/case.py", line 1113, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib64/python3.13/unittest/case.py", line 1095, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib64/python3.13/unittest/case.py", line 732, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: [] != ['acquire', 'acquire', 'release', 'release']

Second list contains 4 additional elements.
First extra element 0:
'acquire'

- []
+ ['acquire', 'acquire', 'release', 'release']

------
2024-05-11T11:12:45 INFO root An info message
------
2024-05-11T11:12:45 INFO root We see an info message
------
2024-05-11T11:12:45 INFO root Here is another info message
/home/ben/src/forks/ZConfig/src/ZConfig/tests/test_schema2html.py:106: DeprecationWarning: The frontend.OptionParser class will be replaced by a subclass of argparse.ArgumentParser in Docutils 0.21 or later.
  settings=docutils.frontend.OptionParser(
/usr/lib64/python3.13/optparse.py:1000: DeprecationWarning: The frontend.Option class will be removed in Docutils 0.21 or later.
  option = self.option_class(*args, **kwargs)
/home/ben/src/forks/ZConfig/src/ZConfig/tests/test_schema2html.py:106: DeprecationWarning: The frontend.OptionParser class will be replaced by a subclass of argparse.ArgumentParser in Docutils 0.21 or later.
  settings=docutils.frontend.OptionParser(
/usr/lib64/python3.13/optparse.py:1000: DeprecationWarning: The frontend.Option class will be removed in Docutils 0.21 or later.
  option = self.option_class(*args, **kwargs)
/home/ben/src/forks/ZConfig/src/ZConfig/tests/test_schema2html.py:106: DeprecationWarning: The frontend.OptionParser class will be replaced by a subclass of argparse.ArgumentParser in Docutils 0.21 or later.
  settings=docutils.frontend.OptionParser(
/usr/lib64/python3.13/optparse.py:1000: DeprecationWarning: The frontend.Option class will be removed in Docutils 0.21 or later.
  option = self.option_class(*args, **kwargs)
/home/ben/src/forks/ZConfig/src/ZConfig/tests/test_schema2html.py:106: DeprecationWarning: The frontend.OptionParser class will be replaced by a subclass of argparse.ArgumentParser in Docutils 0.21 or later.
  settings=docutils.frontend.OptionParser(
/usr/lib64/python3.13/optparse.py:1000: DeprecationWarning: The frontend.Option class will be removed in Docutils 0.21 or later.
  option = self.option_class(*args, **kwargs)
/home/ben/src/forks/ZConfig/src/ZConfig/tests/test_schema2html.py:106: DeprecationWarning: The frontend.OptionParser class will be replaced by a subclass of argparse.ArgumentParser in Docutils 0.21 or later.
  settings=docutils.frontend.OptionParser(
/usr/lib64/python3.13/optparse.py:1000: DeprecationWarning: The frontend.Option class will be removed in Docutils 0.21 or later.
  option = self.option_class(*args, **kwargs)
```

### What version of Python and Zope/Addons I am using:

Fedora Linux 39, Python 3.13.0a6, Zope versions as installed to the virtualenv by default: zope.exceptions 5.0.1, zope.interface  6.3, zope.testrunner 6.4

-----

It wasn’t immediately obvious to me what the best way to fix this should be. I believe it may be related to https://github.com/python/cpython/issues/109461 / https://github.com/python/cpython/pull/109462 / https://github.com/python/cpython/pull/109462.

### PR DESCRIPTION
**Pull request by icemac**
Dependencies:

- [x] Release of [zope.interface](https://github.com/zopefoundation/zope.interface/pull/294) to be able to run on Python 3.13b1
- [x] Fix the problem reported in #96

Fixes #96

### CODE REVIEW

**Comment by dataflake** [comment]
zope.interface release 6.4 is now published.

**Comment by icemac** [comment]
I do not plan to work on fixing this issue, as I have no clue what is going wrong here.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-5-16 00:07 -0700:
>I do not plan to work on fixing this issue, as I have no clue what is going wrong here.

The test
`ZConfig.components.logger.tests.test_logger.TestReopeningLogfiles.test_filehandler_reopen_thread_safety`)
tries to check (among others) that the `close` operation
of `ZConfig.components.logger.loghandler.FileHandler` (derived
from `logging.FileHandler`) uses a lock (to obtain thread safety).
For this, it overrides the `acquire` and `release` methods of
its handler instance.
But, with Python 3.13, the inherited `close` no longer uses
its `acquire/release` methods internally; instead it uses
`with self.lock`. Correspondingly, the test's overrides are ineffective
and the test fails (to recognize that thread safety is still guaranteed).

Likely fix:
do not override `acquire/release` but the `lock` attribute
with a lock mockup recording acquire/release independently
of whether the operations are called under their name or under
`__enter__, __exit__`.

**Review by tseaver — CHANGES_REQUESTED** [review]
The fix LGTM.

@d-maurer, I noticed that you removed a changelog entry.  Shouldn't we have an entry , `- Added support for Python 3.13`, as well as adding the corresponding Trove classifier to `setup.py`?

**Review by tseaver — APPROVED** [review]

**Comment by musicinmybrain** [comment]
Thanks! This fix works for me.

**Comment by d-maurer** [comment]
Tres Seaver wrote at 2024-5-18 06:36 -0700:
>@tseaver requested changes on this pull request.
> ...
>@d-maurer, I noticed that you removed a changelog entry.

I removed a changelog entry which came from my previous work
from PR #98 -- and has been inappropriate here.

> Shouldn't we have an entry
>, `- Added support for Python 3.13`

We should!

The current PR is still a draft and some fine points are still
missing (changelog entry, trove classifiers, ...).

Let's wait until @icemac declares the PR ready for review.

**Comment by tseaver** [comment]
@d-maurer Oops, I saw that we had finished all the issues @icemac noted, and went ahead and added them before merging.  Sorry for being too quick on the trigger.

**Comment by icemac** [comment]
Thank you for the work to fix this PR.

**Pull request merged**
