### PR TITLE
Test on pypy as well

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by gforcada** [comment]
@jamadden I wasn't unsure which version of pypy3 supports travis, it would be cool if there is a way to tests a newer one ...

I will add the changelog entry.

**Comment by jamadden** [comment]
> @jamadden I wasn't unsure which version of pypy3 supports travis, it would be cool if there is a way to tests a newer one ...

There [might be](https://github.com/travis-ci/travis-ci/issues/6277) but I've actually never tried that (I've manually used pyvenv to great effect to acheive the same thing in [relstorage](https://github.com/zodb/relstorage/blob/master/.travis.yml), but that might be overkill).

However, if these versions work, I'm good to go with them until such time as they become a bottleneck. (Commonly in other projects, they need updated because of SSL issues.)

**Comment by mgedmin** [comment]
> Personally, I probably wouldn't have added pypy3, since the travis version is ancient and only supports Python 3.2, a version this project just explicitly dropped. However, it runs, amazingly, and there is precedent for continuing to support this old version of pypy3 as long as that's true.

A common reason to require Python 3.3 is because of `u"..."` literals, and PyPy3 3.2 happens to support these.

**Comment by icemac** [comment]
`VERSION=pypy3.3-5.2-alpha1` should use an updated PyPy3 version according to [travis-ci#6277]https://github.com/travis-ci/travis-ci/issues/6277#issuecomment-232140632).

**Pull request merged**
