### PR TITLE
Add keywords and fix manifest.in and CHANGES.rst

### LINKED ISSUE #32: Fix pyroma and check-manifest
Both produce minor warnings:
```
$ pyroma -a .
------------------------------
Checking .
Found ZConfig
------------------------------
Your package does not have keywords data.
------------------------------
Final rating: 9/10
Cottage Cheese
------------------------------
```

And 
```
$ check-manifest
lists of files in version control and sdist do not match!
missing from sdist:
  .coveragerc
  .readthedocs.yml
  doc/root-and-child-config.conf
  doc/simple-root-config.conf
suggested MANIFEST.in rules:
  include *.yml
  include .coveragerc
  recursive-include doc *.conf
```

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #32

### CODE REVIEW

**Comment by freddrake** [comment]
Theories are wonderful & mysterious, but not always meaningful.  I don't object to providing keywords, but don't expect them to matter.

LGTM

**Comment by jamadden** [comment]
Thank you. 

I wonder if it is about time for a PyPI release? There seem to be some accumulated changes.

**Comment by freddrake** [comment]
What's your PyPI id?

**Comment by jamadden** [comment]
`jamadden`

**Comment by freddrake** [comment]
You now have the powers.

**Comment by jamadden** [comment]
Cool, thank you!

**Pull request merged**
