### PR TITLE
Allow to do variable substitution through environment variables

### PR DESCRIPTION
**Pull request by frapell**
Not much to say here, added ability for ZConfig to expand variables using environment variables through the use of $( ) syntax e.g: $(PATH)

### CODE REVIEW

**Comment by ericof** [comment]
+1 for this pull request.

**Comment by cleberjsantos** [comment]
+1 :)

**Comment by jimfulton** [comment]
@freddrake I think an approach, like this one, that doesn't require changes to application code is much better.

This change would be especially useful for docker-based deployments.

/me sweet-talks fred.

**Comment by sneridagh** [comment]
+1

**Comment by pbauer** [comment]
Since most people agree with this solution, I'll go ahead and merge it.

**Comment by datakurre** [comment]
@pbauer W00t! Please, make this in Plone 5!

**Comment by zupo** [comment]
Great!

**Pull request merged**
